# Generated by Django 3.1.1 on 2020-09-04 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('date_enrolled', models.DateField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=255)),
                ('phone_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('age', models.IntegerField()),
                ('date_recruited', models.DateField(default=datetime.datetime.now)),
                ('course', models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Geography', 'Geography')], max_length=255)),
                ('qualification', models.CharField(choices=[('NCE', 'NCE'), ('HND', 'HND'), ('BSc', 'BSc')], max_length=255)),
                ('position', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_num', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField()),
                ('english', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('biology', models.IntegerField()),
                ('geography', models.IntegerField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmgt.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmgt.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField()),
                ('english', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('biology', models.IntegerField()),
                ('geography', models.IntegerField()),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmgt.student')),
            ],
        ),
    ]
